import Testing
import AppKit
import Foundation
@testable import DrobuCore

@Suite("ClipboardMonitor.extractRecord")
@MainActor
struct ClipboardMonitorExtractRecordTests {

    private let monitor = ClipboardMonitor(database: try! makeTestDatabase())

    // MARK: - Text Extraction

    @Test func extractsTextRecord() {
        let item = MockPasteboardItem.text("hello world")
        let record = monitor.extractRecord(from: item, sourceApp: "Safari", sourceBundleId: "com.apple.Safari")

        #expect(record != nil)
        #expect(record?.kind == ClipboardRecord.kindText)
        #expect(record?.plainText == "hello world")
        #expect(record?.sourceApp == "Safari")
        #expect(record?.sourceBundleId == "com.apple.Safari")
    }

    @Test func trimsWhitespaceFromText() {
        let item = MockPasteboardItem.text("  hello world  \n\n")
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record?.plainText == "hello world")
    }

    @Test func stripsANSIEscapeSequences() {
        let item = MockPasteboardItem.text("\u{1B}[31mred text\u{1B}[0m")
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record?.plainText == "red text")
    }

    @Test func rejectsEmptyTextAfterTrim() {
        let item = MockPasteboardItem.text("   \n\n  ")
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record == nil)
    }

    @Test func rejectsTextExceeding1MBSizeLimit() {
        let largeText = String(repeating: "a", count: 1_000_001)
        let item = MockPasteboardItem.text(largeText)
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record == nil)
    }

    @Test func computesCorrectSHA256Hash() {
        let item = MockPasteboardItem.text("test content")
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        let expectedHash = Data("test content".utf8).sha256String
        #expect(record?.contentHash == expectedHash)
    }

    // MARK: - GIF Extraction

    @Test func extractsGIFRecord() {
        // Minimal valid GIF data (GIF89a header + minimal content)
        let gifData = makeMinimalGIFData()
        let item = MockPasteboardItem.gif(gifData)
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record != nil)
        #expect(record?.kind == ClipboardRecord.kindGif)
        #expect(record?.imageData == gifData)
        #expect(record?.contentHash == gifData.sha256String)
    }

    @Test func rejectsGIFExceeding20MBSizeLimit() {
        let largeGIF = Data(repeating: 0x47, count: 20_000_001) // Just over 20MB
        let item = MockPasteboardItem.gif(largeGIF)
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record == nil)
    }

    // MARK: - Image Extraction

    @Test func extractsImageFromPNGData() {
        let pngData = makeMinimalPNGData()
        let item = MockPasteboardItem.image(pngData)
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record != nil)
        #expect(record?.kind == ClipboardRecord.kindImage)
        #expect(record?.imageData == pngData)
    }

    @Test func rejectsImageExceeding10MBSizeLimit() {
        let largeImage = Data(repeating: 0x89, count: 10_000_001)
        let item = MockPasteboardItem.image(largeImage)
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record == nil)
    }

    // MARK: - Kind Priority

    @Test func gifTakesPriorityOverText() {
        let gifData = makeMinimalGIFData()
        let item = MockPasteboardItem(
            types: [.gif, .string],
            data: [.gif: gifData],
            strings: [.string: "some text"]
        )
        let record = monitor.extractRecord(from: item, sourceApp: nil, sourceBundleId: nil)

        #expect(record?.kind == ClipboardRecord.kindGif)
    }

    // MARK: - shouldIgnoreTypes

    @Test func shouldIgnoreTransientType() {
        #expect(ClipboardMonitor.shouldIgnoreTypes(["public.utf8-plain-text", "org.nspasteboard.TransientType"]))
    }

    @Test func shouldIgnoreConcealedType() {
        #expect(ClipboardMonitor.shouldIgnoreTypes(["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
    }

    @Test func shouldIgnoreAutoGeneratedType() {
        #expect(ClipboardMonitor.shouldIgnoreTypes(["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"]))
    }

    @Test func shouldIgnore1PasswordType() {
        #expect(ClipboardMonitor.shouldIgnoreTypes(["public.utf8-plain-text", "com.agilebits.onepassword"]))
    }

    @Test func shouldNotIgnoreNormalTypes() {
        #expect(!ClipboardMonitor.shouldIgnoreTypes(["public.utf8-plain-text", "public.png"]))
    }
}

// MARK: - Test Fixtures

/// Create a minimal valid GIF (1x1 pixel, single frame)
private func makeMinimalGIFData() -> Data {
    // GIF89a 1x1 pixel with global color table
    let bytes: [UInt8] = [
        0x47, 0x49, 0x46, 0x38, 0x39, 0x61, // GIF89a
        0x01, 0x00, 0x01, 0x00, // 1x1
        0x80, 0x00, 0x00,       // GCT flag, 2 colors
        0x00, 0x00, 0x00,       // color 0: black
        0xFF, 0xFF, 0xFF,       // color 1: white
        0x2C, 0x00, 0x00, 0x00, 0x00, // image descriptor
        0x01, 0x00, 0x01, 0x00, 0x00, // 1x1
        0x02, 0x02, 0x44, 0x01, 0x00, // LZW min code size + data
        0x3B                     // trailer
    ]
    return Data(bytes)
}

/// Create minimal PNG data (1x1 pixel)
private func makeMinimalPNGData() -> Data {
    // Create a 1x1 red pixel NSImage and export as PNG
    let image = NSImage(size: NSSize(width: 1, height: 1))
    image.lockFocus()
    NSColor.red.set()
    NSRect(x: 0, y: 0, width: 1, height: 1).fill()
    image.unlockFocus()

    guard let tiffData = image.tiffRepresentation,
          let bitmap = NSBitmapImageRep(data: tiffData),
          let pngData = bitmap.representation(using: .png, properties: [:]) else {
        // Fallback: return raw bytes that at least have PNG header
        return Data([0x89, 0x50, 0x4E, 0x47])
    }
    return pngData
}
