import AppKit
import CryptoKit
import GRDB
import Foundation

@MainActor
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard = NSPasteboard.general
    private let database: AppDatabase
    private var isSuppressed = false

    var onAccessDenied: (() -> Void)?

    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    init(database: AppDatabase) {
        self.database = database
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
        RunLoop.current.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func suppressNextChange() {
        isSuppressed = true
    }

    private func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if isSuppressed {
            isSuppressed = false
            return
        }

        guard let items = pasteboard.pasteboardItems else {
            // Poll failure may indicate pasteboard privacy denial (macOS 15.4+)
            if pasteboard.responds(to: NSSelectorFromString("accessBehavior")),
               let rawValue = pasteboard.value(forKey: "accessBehavior") as? Int,
               rawValue != 0 {
                onAccessDenied?()
            }
            return
        }
        for item in items {
            let typeStrings = item.types.map(\.rawValue)

            // Skip concealed/transient types (password managers, etc.)
            if typeStrings.contains(where: { Self.ignoredTypes.contains($0) }) {
                continue
            }

            // Extract content on main thread (NSPasteboard requires it)
            if let record = extractRecord(from: item) {
                // Write to DB on background task
                let db = database
                Task.detached {
                    try? await db.pool.write { dbConn in
                        try ClipboardRecord.upsert(record, in: dbConn)
                    }
                }
            }
        }
    }

    private func extractRecord(from item: NSPasteboardItem) -> ClipboardRecord? {
        let types = item.types
        let frontmost = NSWorkspace.shared.frontmostApplication
        let sourceApp = frontmost?.localizedName
        let sourceBundleId = frontmost?.bundleIdentifier

        // Priority: text > image (per plan — text preferred when both present)
        if types.contains(.string), let text = item.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            guard trimmed.utf8.count <= 1_000_000 else { return nil } // 1MB cap

            let hash = sha256(trimmed.data(using: .utf8)!)
            return ClipboardRecord(
                kind: ClipboardRecord.kindText,
                plainText: trimmed,
                imageData: nil,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        if let imageData = item.data(forType: .png) ?? item.data(forType: .tiff) {
            guard imageData.count <= 10_000_000 else { return nil } // 10MB cap

            let hash = sha256(imageData)
            return ClipboardRecord(
                kind: ClipboardRecord.kindImage,
                plainText: sourceApp, // Store source app in plainText for FTS searchability
                imageData: imageData,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        return nil
    }

    private func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
