import AppKit
import GRDB
import Foundation

@MainActor
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard = NSPasteboard.general
    private let database: AppDatabase
    private var suppressCount = 0

    var onAccessDenied: (() -> Void)?

    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    init(database: AppDatabase) {
        self.database = database
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
        if let timer { RunLoop.current.add(timer, forMode: .common) }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func suppressNextChange() {
        suppressCount = 1
    }

    func suppressChanges(count: Int) {
        suppressCount = count
    }

    private func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if suppressCount > 0 {
            suppressCount -= 1
            Log.debug("ClipboardMonitor: change \(lastChangeCount - 1)→\(lastChangeCount), suppressed (remaining: \(suppressCount))")
            return
        }

        guard let items = pasteboard.pasteboardItems else {
            Log.debug("ClipboardMonitor: pasteboardItems nil")
            // Poll failure may indicate pasteboard privacy denial (macOS 15.4+)
            if pasteboard.responds(to: NSSelectorFromString("accessBehavior")),
               let rawValue = pasteboard.value(forKey: "accessBehavior") as? Int,
               rawValue != 0 {
                onAccessDenied?()
            }
            return
        }
        let frontApp = NSWorkspace.shared.frontmostApplication
        Log.debug("ClipboardMonitor: change \(lastChangeCount - 1)→\(lastChangeCount) from \(frontApp?.localizedName ?? "unknown") (\(frontApp?.bundleIdentifier ?? "?")), types: [\(items.flatMap { $0.types.map(\.rawValue) }.joined(separator: ", "))]")
        for item in items {
            let typeStrings = item.types.map(\.rawValue)

            // Skip concealed/transient types (password managers, etc.)
            if typeStrings.contains(where: { Self.ignoredTypes.contains($0) }) {
                Log.debug("ClipboardMonitor: skipped — concealed type: \(typeStrings.filter { Self.ignoredTypes.contains($0) }.joined(separator: ", "))")
                continue
            }

            // Extract content on main thread (NSPasteboard requires it)
            if let record = extractRecord(from: item) {
                Log.debug("ClipboardMonitor: captured \(record.kind) (\(record.imageData?.count ?? record.plainText?.utf8.count ?? 0) bytes) hash=\(record.contentHash.prefix(8))")
                // Write to DB on background task
                let db = database
                Task.detached {
                    do {
                        _ = try await db.pool.write { dbConn in
                            try ClipboardRecord.upsert(record, in: dbConn)
                        }
                    } catch {
                        Log.error("ClipboardMonitor: upsert failed: \(error)")
                    }
                }
            } else {
                Log.debug("ClipboardMonitor: no extractable content, types: [\(typeStrings.joined(separator: ", "))]")
            }
        }
    }

    /// Strip ANSI escape sequences (CSI, OSC) from text.
    private static func stripANSI(_ text: String) -> String {
        // CSI: \x1B[ followed by parameter bytes and a letter
        // OSC: \x1B] followed by content terminated by BEL (\x07) or ST (\x1B\\)
        text.replacingOccurrences(
            of: "\u{1B}(?:\\[[0-9;]*[A-Za-z]|\\][^\u{07}]*(?:\u{07}|\u{1B}\\\\))",
            with: "",
            options: .regularExpression
        )
    }

    private func extractRecord(from item: NSPasteboardItem) -> ClipboardRecord? {
        let types = item.types
        let frontmost = NSWorkspace.shared.frontmostApplication
        let sourceApp = frontmost?.localizedName
        let sourceBundleId = frontmost?.bundleIdentifier

        // 1. Check for GIF — both raw data and file URLs (e.g. copying .gif from Finder)
        if let gifData = item.data(forType: .gif) {
            guard gifData.count <= 20_000_000 else {
                Log.debug("ClipboardMonitor: GIF too large (\(gifData.count / 1_000_000)MB)")
                return nil
            }

            let hash = gifData.sha256String
            return ClipboardRecord(
                kind: ClipboardRecord.kindGif,
                plainText: sourceApp,
                imageData: gifData,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        // Check for file URL pointing to a .gif file (Finder copies files as URLs, not raw data)
        if let fileURLString = item.string(forType: .fileURL),
           let fileURL = URL(string: fileURLString),
           fileURL.scheme == "file",
           fileURL.pathExtension.lowercased() == "gif" {
            if let gifData = try? Data(contentsOf: fileURL) {
                guard gifData.count <= 20_000_000 else {
                    Log.debug("ClipboardMonitor: GIF too large (\(gifData.count / 1_000_000)MB)")
                    return nil
                }

                let hash = gifData.sha256String
                return ClipboardRecord(
                    kind: ClipboardRecord.kindGif,
                    plainText: sourceApp,
                    imageData: gifData,
                    sourceApp: sourceApp,
                    sourceBundleId: sourceBundleId,
                    contentHash: hash,
                    createdAt: Date()
                )
            }
        }

        // 2. Text
        if types.contains(.string), let text = item.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else {
                Log.debug("ClipboardMonitor: empty after trim")
                return nil
            }

            // Strip ANSI escape sequences (terminal color codes, cursor control, OSC)
            let cleaned = Self.stripANSI(trimmed)
            guard !cleaned.isEmpty else {
                Log.debug("ClipboardMonitor: empty after ANSI strip")
                return nil
            }
            guard cleaned.utf8.count <= 1_000_000 else {
                Log.debug("ClipboardMonitor: text too large (\(cleaned.utf8.count / 1000)KB)")
                return nil
            }

            let hash = cleaned.data(using: .utf8)!.sha256String
            return ClipboardRecord(
                kind: ClipboardRecord.kindText,
                plainText: cleaned,
                imageData: nil,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        if let imageData = item.data(forType: .png) ?? item.data(forType: .tiff) {
            guard imageData.count <= 10_000_000 else {
                Log.debug("ClipboardMonitor: image too large (\(imageData.count / 1_000_000)MB)")
                return nil
            }

            let hash = imageData.sha256String
            return ClipboardRecord(
                kind: ClipboardRecord.kindImage,
                plainText: sourceApp, // Store source app in plainText for FTS searchability
                imageData: imageData,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        return nil
    }

}
