import AppKit
import GRDB
import Foundation

@MainActor
protocol PasteboardItemReading {
    var types: [NSPasteboard.PasteboardType] { get }
    func data(forType type: NSPasteboard.PasteboardType) -> Data?
    func string(forType type: NSPasteboard.PasteboardType) -> String?
}

extension NSPasteboardItem: PasteboardItemReading {}

@MainActor
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard = NSPasteboard.general
    private let database: AppDatabase
    private var suppressCount = 0

    var onAccessDenied: (() -> Void)?

    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Check if pasteboard types contain concealed/transient types that should be skipped.
    static func shouldIgnoreTypes(_ typeStrings: [String]) -> Bool {
        typeStrings.contains(where: { ignoredTypes.contains($0) })
    }

    init(database: AppDatabase) {
        self.database = database
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
        if let timer { RunLoop.current.add(timer, forMode: .common) }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func suppressNextChange() {
        suppressCount = 1
    }

    func suppressChanges(count: Int) {
        suppressCount = count
    }

    private func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if suppressCount > 0 {
            suppressCount -= 1
            Log.debug("ClipboardMonitor: change \(lastChangeCount - 1)→\(lastChangeCount), suppressed (remaining: \(suppressCount))")
            return
        }

        guard let items = pasteboard.pasteboardItems else {
            Log.debug("ClipboardMonitor: pasteboardItems nil")
            // Poll failure may indicate pasteboard privacy denial (macOS 15.4+)
            if pasteboard.responds(to: NSSelectorFromString("accessBehavior")),
               let rawValue = pasteboard.value(forKey: "accessBehavior") as? Int,
               rawValue != 0 {
                onAccessDenied?()
            }
            return
        }
        let frontApp = NSWorkspace.shared.frontmostApplication
        Log.debug("ClipboardMonitor: change \(lastChangeCount - 1)→\(lastChangeCount) from \(frontApp?.localizedName ?? "unknown") (\(frontApp?.bundleIdentifier ?? "?")), types: [\(items.flatMap { $0.types.map(\.rawValue) }.joined(separator: ", "))]")

        // Pre-scan: detect file URLs across all items (Finder puts one item per file)
        let fileItems = items.filter { item in
            guard let urlString = item.string(forType: .fileURL),
                  let url = URL(string: urlString),
                  url.scheme == "file",
                  url.pathExtension.lowercased() != "gif" else { return false }
            return true
        }

        // If ALL items are file URLs → create single grouped file record, skip per-item loop
        if !fileItems.isEmpty && fileItems.count == items.count {
            // Filter out any items with concealed/transient types (check ALL items, not just first)
            let safeFileItems = fileItems.filter { item in
                !Self.shouldIgnoreTypes(item.types.map(\.rawValue))
            }
            guard !safeFileItems.isEmpty else {
                Log.debug("ClipboardMonitor: skipped file URLs — concealed type")
                return
            }

            let paths = safeFileItems.compactMap { item -> String? in
                guard let urlString = item.string(forType: .fileURL),
                      let url = URL(string: urlString) else { return nil }
                return url.path
            }.sorted()
            guard !paths.isEmpty else { return }

            let joined = paths.joined(separator: "\n")
            let hash = Data(joined.utf8).sha256String
            let sourceApp = frontApp?.localizedName
            let sourceBundleId = frontApp?.bundleIdentifier

            let record = ClipboardRecord(
                kind: ClipboardRecord.kindFile,
                plainText: joined,
                imageData: nil,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )

            Log.debug("ClipboardMonitor: captured file (\(paths.count) path(s), \(joined.utf8.count) bytes) hash=\(hash.prefix(8))")
            let db = database
            Task.detached {
                do {
                    _ = try await db.pool.write { dbConn in
                        try ClipboardRecord.upsert(record, in: dbConn)
                    }
                } catch {
                    Log.error("ClipboardMonitor: upsert failed: \(error)")
                }
            }
            return
        }

        // Mixed pasteboard: capture file-URL items as a file record, then process the rest
        // Filter out concealed/transient file items (same privacy guard as the per-item loop)
        let nonConcealedFileItems = fileItems.filter { item in
            !Self.shouldIgnoreTypes(item.types.map(\.rawValue))
        }
        let fileItemIds = Set(fileItems.map { ObjectIdentifier($0) })
        if !nonConcealedFileItems.isEmpty {
            let paths = nonConcealedFileItems.compactMap { item -> String? in
                guard let urlString = item.string(forType: .fileURL),
                      let url = URL(string: urlString) else { return nil }
                return url.path
            }.sorted()
            if !paths.isEmpty {
                let joined = paths.joined(separator: "\n")
                let hash = Data(joined.utf8).sha256String
                let sourceApp = frontApp?.localizedName
                let sourceBundleId = frontApp?.bundleIdentifier
                let record = ClipboardRecord(
                    kind: ClipboardRecord.kindFile,
                    plainText: joined,
                    imageData: nil,
                    sourceApp: sourceApp,
                    sourceBundleId: sourceBundleId,
                    contentHash: hash,
                    createdAt: Date()
                )
                Log.debug("ClipboardMonitor: captured file from mixed pasteboard (\(paths.count) path(s)) hash=\(hash.prefix(8))")
                let db = database
                Task.detached {
                    do {
                        _ = try await db.pool.write { dbConn in
                            try ClipboardRecord.upsert(record, in: dbConn)
                        }
                    } catch {
                        Log.error("ClipboardMonitor: upsert failed: \(error)")
                    }
                }
            }
        }

        for item in items {
            // Skip items already captured as file URLs above
            if fileItemIds.contains(ObjectIdentifier(item)) {
                continue
            }

            let typeStrings = item.types.map(\.rawValue)

            // Skip concealed/transient types (password managers, etc.)
            if Self.shouldIgnoreTypes(typeStrings) {
                Log.debug("ClipboardMonitor: skipped — concealed type: \(typeStrings.filter { Self.ignoredTypes.contains($0) }.joined(separator: ", "))")
                continue
            }

            // Extract content on main thread (NSPasteboard requires it)
            let sourceApp = frontApp?.localizedName
            let sourceBundleId = frontApp?.bundleIdentifier
            if let record = extractRecord(from: item, sourceApp: sourceApp, sourceBundleId: sourceBundleId) {
                Log.debug("ClipboardMonitor: captured \(record.kind) (\(record.imageData?.count ?? record.plainText?.utf8.count ?? 0) bytes) hash=\(record.contentHash.prefix(8))")
                // Write to DB on background task
                let db = database
                Task.detached {
                    do {
                        _ = try await db.pool.write { dbConn in
                            try ClipboardRecord.upsert(record, in: dbConn)
                        }
                    } catch {
                        Log.error("ClipboardMonitor: upsert failed: \(error)")
                    }
                }
            } else {
                Log.debug("ClipboardMonitor: no extractable content, types: [\(typeStrings.joined(separator: ", "))]")
            }
        }
    }

    func extractRecord(from item: any PasteboardItemReading, sourceApp: String?, sourceBundleId: String?) -> ClipboardRecord? {
        let types = item.types

        // 1. Check for GIF — both raw data and file URLs (e.g. copying .gif from Finder)
        if let gifData = item.data(forType: .gif) {
            guard gifData.count <= 20_000_000 else {
                Log.debug("ClipboardMonitor: GIF too large (\(gifData.count / 1_000_000)MB)")
                return nil
            }

            let hash = gifData.sha256String
            return ClipboardRecord(
                kind: ClipboardRecord.kindGif,
                plainText: ClipboardRecord.mediaDisplayText(from: gifData, kind: ClipboardRecord.kindGif),
                imageData: gifData,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        // Check for file URL pointing to a .gif file (Finder copies files as URLs, not raw data)
        if let fileURLString = item.string(forType: .fileURL),
           let fileURL = URL(string: fileURLString),
           fileURL.scheme == "file",
           fileURL.pathExtension.lowercased() == "gif" {
            if let gifData = try? Data(contentsOf: fileURL) {
                guard gifData.count <= 20_000_000 else {
                    Log.debug("ClipboardMonitor: GIF too large (\(gifData.count / 1_000_000)MB)")
                    return nil
                }

                let hash = gifData.sha256String
                return ClipboardRecord(
                    kind: ClipboardRecord.kindGif,
                    plainText: ClipboardRecord.mediaDisplayText(from: gifData, kind: ClipboardRecord.kindGif),
                    imageData: gifData,
                    sourceApp: sourceApp,
                    sourceBundleId: sourceBundleId,
                    contentHash: hash,
                    createdAt: Date()
                )
            }
        }

        // 2. Text
        if types.contains(.string), let text = item.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else {
                Log.debug("ClipboardMonitor: empty after trim")
                return nil
            }

            // Strip ANSI escape sequences (terminal color codes, cursor control, OSC)
            let stripped = TerminalTextCleaner.stripANSI(trimmed)
            guard !stripped.isEmpty else {
                Log.debug("ClipboardMonitor: empty after ANSI strip")
                return nil
            }

            // Auto-unwrap hard-wrapped prose (e.g. CLI output) when the text
            // doesn't look like code, YAML, or shell. Skipped content can
            // still be cleaned manually via the edit-mode hotkey.
            let cleaned: String
            if TerminalTextCleaner.shouldAutoClean(stripped) {
                cleaned = TerminalTextCleaner.clean(stripped)
                Log.debug("ClipboardMonitor: auto-cleaned wrapped text from \(sourceApp ?? "unknown")")
            } else {
                cleaned = stripped
            }

            guard cleaned.utf8.count <= 1_000_000 else {
                Log.debug("ClipboardMonitor: text too large (\(cleaned.utf8.count / 1000)KB)")
                return nil
            }

            let hash = Data(cleaned.utf8).sha256String
            return ClipboardRecord(
                kind: ClipboardRecord.kindText,
                plainText: cleaned,
                imageData: nil,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        if let imageData = item.data(forType: .png) ?? item.data(forType: .tiff) {
            guard imageData.count <= 10_000_000 else {
                Log.debug("ClipboardMonitor: image too large (\(imageData.count / 1_000_000)MB)")
                return nil
            }

            let hash = imageData.sha256String
            return ClipboardRecord(
                kind: ClipboardRecord.kindImage,
                plainText: ClipboardRecord.mediaDisplayText(from: imageData, kind: ClipboardRecord.kindImage),
                imageData: imageData,
                sourceApp: sourceApp,
                sourceBundleId: sourceBundleId,
                contentHash: hash,
                createdAt: Date()
            )
        }

        return nil
    }

}
